<x-filament-panels::page>
    <div class="space-y-6">
        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <div class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900"><div class="flex items-start justify-between"><p class="text-sm font-medium text-gray-500">Status API</p><x-filament::icon icon="heroicon-o-signal" class="h-5 w-5 {{ ($connectionResult['connected'] ?? false) ? 'text-success-600' : 'text-gray-400' }}" /></div><p class="mt-3 font-semibold {{ ($connectionResult['connected'] ?? false) ? 'text-success-600' : 'text-danger-600' }}">{{ ($connectionResult['connected'] ?? false) ? 'Terhubung' : 'Tidak Terhubung' }}</p><p class="mt-1 truncate text-xs text-gray-500">{{ $connectionResult['phone'] ?? 'Belum diuji' }}</p></div>
            <div class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900"><p class="text-sm font-medium text-gray-500">Pesan Bulan Ini</p><p class="mt-3 text-2xl font-semibold">{{ $this->messageStats['total'] }}</p></div>
            <div class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900"><p class="text-sm font-medium text-gray-500">Berhasil Dikirim</p><p class="mt-3 text-2xl font-semibold text-success-600">{{ $this->messageStats['sent'] }}</p></div>
            <div class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900"><p class="text-sm font-medium text-gray-500">Gagal</p><p class="mt-3 text-2xl font-semibold text-danger-600">{{ $this->messageStats['failed'] }}</p></div>
        </div>

        <x-filament::section heading="Buat Siaran WhatsApp" description="Pilih templat dan penerima. Pesan akan diproses di latar belakang melalui antrean." icon="heroicon-o-paper-airplane">
            <div class="grid grid-cols-1 gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(320px,0.85fr)]">
                <div class="space-y-5">
                    <label class="block space-y-2"><span class="text-sm font-medium text-gray-700 dark:text-gray-200">Judul Internal</span><input wire:model="broadcastTitle" type="text" maxlength="255" class="block w-full rounded-lg border-gray-300 bg-white px-3 py-2.5 text-sm shadow-sm focus:border-primary-500 focus:ring-primary-500 dark:border-gray-700 dark:bg-gray-900" placeholder="Contoh: Pengingat Agustus" /></label>
                    <label class="block space-y-2"><span class="text-sm font-medium text-gray-700 dark:text-gray-200">Templat Pesan</span><select wire:model.live="templateId" class="block w-full rounded-lg border-gray-300 bg-white px-3 py-2.5 text-sm shadow-sm focus:border-primary-500 focus:ring-primary-500 dark:border-gray-700 dark:bg-gray-900">@foreach ($this->templates as $template)<option wire:key="template-{{ $template->id }}" value="{{ $template->id }}">{{ $template->display_name }}</option>@endforeach</select></label>
                    <label class="block space-y-2"><span class="text-sm font-medium text-gray-700 dark:text-gray-200">Kelompok Penerima</span><select wire:model.live="audience" class="block w-full rounded-lg border-gray-300 bg-white px-3 py-2.5 text-sm shadow-sm focus:border-primary-500 focus:ring-primary-500 dark:border-gray-700 dark:bg-gray-900"><option value="all">Semua Penghuni</option><option value="unpaid">Belum Bayar</option><option value="overdue">Terlambat</option><option value="manual">Pilih Manual</option></select></label>
                    @if ($audience === 'manual')<label class="block space-y-2"><span class="text-sm font-medium text-gray-700 dark:text-gray-200">Pilih Penghuni</span><select wire:model.live="manualTenantIds" multiple class="block min-h-40 w-full rounded-lg border-gray-300 bg-white px-3 py-2.5 text-sm shadow-sm focus:border-primary-500 focus:ring-primary-500 dark:border-gray-700 dark:bg-gray-900">@foreach ($this->tenants as $tenant)<option wire:key="tenant-{{ $tenant->id }}" value="{{ $tenant->id }}">{{ $tenant->name }}</option>@endforeach</select><span class="text-xs text-gray-500">Gunakan Ctrl atau Cmd untuk memilih lebih dari satu penghuni.</span></label>@endif
                </div>
                <div class="rounded-xl border border-gray-200 bg-gray-50 p-5 dark:border-gray-700 dark:bg-gray-950"><div class="flex items-center justify-between gap-3"><p class="text-sm font-semibold text-gray-900 dark:text-white">Pratinjau Pesan</p><span class="rounded-full bg-primary-100 px-2.5 py-1 text-xs font-medium text-primary-700 dark:bg-primary-950/50 dark:text-primary-300">{{ $this->recipientCount }} penerima</span></div><div class="mt-4 min-h-32 whitespace-pre-wrap rounded-lg border border-gray-200 bg-white p-4 text-sm leading-6 text-gray-700 shadow-sm dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200">{{ $this->preview }}</div><div class="mt-5 grid grid-cols-2 gap-3 border-t border-gray-200 pt-4 text-sm dark:border-gray-700"><div><span class="text-gray-500">Jumlah penerima</span><p class="mt-1 font-semibold text-gray-900 dark:text-white">{{ $this->recipientCount }} orang</p></div><div><span class="text-gray-500">Estimasi pesan</span><p class="mt-1 font-semibold text-gray-900 dark:text-white">{{ $this->recipientCount }} pesan</p></div></div></div>
            </div>
            <div class="mt-6 flex flex-wrap gap-3 border-t border-gray-200 pt-5 dark:border-gray-700"><x-filament::button wire:click="testConnection" color="gray" wire:loading.attr="disabled" wire:target="testConnection" icon="heroicon-o-signal">Uji Koneksi</x-filament::button><x-filament::modal id="confirm-whatsapp-broadcast" width="lg"><x-slot name="trigger"><x-filament::button color="success" :disabled="$this->recipientCount === 0" icon="heroicon-o-paper-airplane">Kirim Siaran</x-filament::button></x-slot><x-slot name="heading">Konfirmasi Siaran WhatsApp</x-slot><p class="text-sm leading-6 text-gray-600 dark:text-gray-300">Anda akan mengirim templat WhatsApp kepada <strong>{{ $this->recipientCount }} penerima</strong>. Proses berjalan melalui antrean.</p><div class="mt-4 rounded-lg bg-gray-50 p-4 text-sm leading-6 dark:bg-gray-900">{{ $this->preview }}</div><x-slot name="footerActions"><x-filament::button color="gray" x-on:click="$dispatch('close-modal', { id: 'confirm-whatsapp-broadcast' })">Batal</x-filament::button><x-filament::button wire:click="sendBroadcast" wire:loading.attr="disabled" wire:target="sendBroadcast" color="success">Kirim Sekarang</x-filament::button></x-slot></x-filament::modal></div>
        </x-filament::section>

        <x-filament::section heading="Siaran Terbaru" description="Riwayat sepuluh siaran terakhir." icon="heroicon-o-clock"><div class="overflow-hidden rounded-xl border border-gray-200 dark:border-gray-700"><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-gray-50 text-xs uppercase tracking-wide text-gray-500 dark:bg-gray-800/60 dark:text-gray-400"><tr><th class="px-4 py-3 font-semibold">Judul</th><th class="px-4 py-3 font-semibold">Kelompok Penerima</th><th class="px-4 py-3 font-semibold">Penerima</th><th class="px-4 py-3 font-semibold">Terkirim</th><th class="px-4 py-3 font-semibold">Gagal</th><th class="px-4 py-3 font-semibold">Status</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@forelse ($this->recentBroadcasts as $broadcast)<tr wire:key="broadcast-{{ $broadcast->id }}" class="text-gray-700 transition hover:bg-gray-50 dark:text-gray-200 dark:hover:bg-gray-800/40"><td class="px-4 py-3 font-medium text-gray-950 dark:text-white">{{ $broadcast->title }}</td><td class="px-4 py-3">{{ $broadcast->audience_type->label() }}</td><td class="px-4 py-3">{{ $broadcast->total_recipient }}</td><td class="px-4 py-3">{{ $broadcast->total_sent }}</td><td class="px-4 py-3">{{ $broadcast->total_failed }}</td><td class="px-4 py-3"><x-filament::badge :color="$broadcast->status->getColor()">{{ $broadcast->status->label() }}</x-filament::badge></td></tr>@empty<tr><td colspan="6" class="px-4 py-14 text-center text-gray-500 dark:text-gray-400">Belum ada siaran.</td></tr>@endforelse</tbody></table></div></div></x-filament::section>
    </div>
</x-filament-panels::page>
