<div class="mx-auto flex max-w-2xl flex-col gap-8">
    <header><a href="{{ route('tenant.invoices.show', $invoice) }}" class="mb-5 inline-flex items-center gap-1 text-sm font-semibold text-[#031636]"><span class="material-symbols-outlined text-lg">arrow_back</span>Detail tagihan</a><h1 class="text-3xl font-semibold tracking-tight">Ajukan Pembayaran</h1><p class="mt-2 text-[#44474e]">Pilih metode dan kirim bukti pembayaran Anda.</p></header>
    <section class="rounded-xl bg-[#eeeeec] p-5"><p class="text-xs font-semibold uppercase tracking-wider text-[#44474e]">Rincian Tagihan</p><div class="mt-3 flex items-end justify-between gap-4"><p>{{ \Carbon\Carbon::create($invoice->period_year, $invoice->period_month)->locale('id')->translatedFormat('F Y') }}</p><p class="text-xl font-semibold">Rp {{ number_format($invoice->total_amount, 0, ',', '.') }}</p></div></section>
    <form wire:submit="submit" class="flex flex-col gap-6">
        <fieldset><legend class="mb-2 text-xs font-semibold uppercase tracking-wider text-[#44474e]">Kategori Pembayaran</legend><div class="grid grid-cols-3 gap-2">@forelse ($paymentCategories as $category)<label wire:key="payment-category-{{ $category->value }}" class="flex cursor-pointer flex-col items-center gap-2 rounded-xl border px-2 py-4 text-center transition {{ $paymentCategory === $category->value ? 'border-[#031636] bg-[#e7e2d8] text-[#031636]' : 'border-[#c5c6cf]/50 bg-[#eeeeec] text-[#44474e]' }}"><input wire:model.live="paymentCategory" type="radio" value="{{ $category->value }}" class="sr-only"><span class="material-symbols-outlined">{{ $category->icon() }}</span><span class="text-xs font-semibold sm:text-sm">{{ $category->label() }}</span></label>@empty<div class="col-span-3 rounded-xl bg-[#ffdad6] p-4 text-sm text-[#93000a]">Belum ada metode pembayaran aktif. Hubungi pengelola kost.</div>@endforelse</div>@error('paymentCategory')<p class="mt-2 text-sm text-[#ba1a1a]">{{ $message }}</p>@enderror</fieldset>
        @if ($paymentCategories->isNotEmpty())<fieldset><legend class="mb-2 text-xs font-semibold uppercase tracking-wider text-[#44474e]">Pilih Tujuan Pembayaran</legend><div class="grid gap-3 sm:grid-cols-2">@foreach ($paymentMethods as $method)<label wire:key="payment-method-{{ $method->id }}" class="flex cursor-pointer items-center justify-between rounded-xl border p-4 transition {{ $paymentMethodId === $method->id ? 'border-[#031636] bg-[#e7e2d8]' : 'border-[#c5c6cf]/50 bg-[#eeeeec]' }}"><input wire:model.live="paymentMethodId" type="radio" value="{{ $method->id }}" class="sr-only"><span class="flex items-center gap-3"><span class="material-symbols-outlined text-[#031636]">{{ $method->category->icon() }}</span><span><span class="block font-medium">{{ $method->name }}</span>@if ($method->account_number)<span class="mt-1 block text-xs text-[#44474e]">{{ $method->account_number }}</span>@endif</span></span>@if ($paymentMethodId === $method->id)<span class="material-symbols-outlined text-[#031636]" style="font-variation-settings: 'FILL' 1">check_circle</span>@endif</label>@endforeach</div>@error('paymentMethodId')<p class="mt-2 text-sm text-[#ba1a1a]">{{ $message }}</p>@enderror</fieldset>@endif
        @if ($selectedPaymentMethod)<section x-data="{ copied: false }" class="rounded-xl bg-[#1a2b4c] p-5 text-[#b6c6f0]"><p class="text-xs font-semibold uppercase tracking-wider opacity-70">{{ $selectedPaymentMethod->name }}</p><div class="mt-4 flex flex-col gap-2">@if ($selectedPaymentMethod->account_number)<div class="flex items-center justify-between gap-4"><p class="text-xl font-semibold tracking-wider text-white">{{ $selectedPaymentMethod->account_number }}</p><button type="button" @click="navigator.clipboard.writeText(@js($selectedPaymentMethod->account_number)); copied = true; setTimeout(() => copied = false, 2000)" class="flex size-10 items-center justify-center rounded-full text-white hover:bg-white/10" aria-label="Salin tujuan pembayaran"><span class="material-symbols-outlined text-xl" x-text="copied ? 'check' : 'content_copy'"></span></button></div>@endif @if ($selectedPaymentMethod->account_holder)<p class="opacity-80">a.n. {{ $selectedPaymentMethod->account_holder }}</p>@endif @if ($selectedPaymentMethod->instructions)<p class="mt-2 whitespace-pre-line text-sm leading-6 text-white/80">{{ $selectedPaymentMethod->instructions }}</p>@endif</div></section>@endif
        <label class="block"><span class="mb-2 block text-xs font-semibold uppercase tracking-wider text-[#44474e]">Bukti Pembayaran</span><span class="flex cursor-pointer flex-col items-center gap-4 rounded-xl bg-[#e7e2d8] p-8 text-center transition hover:bg-[#ddd8ce]"><input wire:model="proof" type="file" accept=".jpg,.jpeg,.png,.webp,.pdf" class="sr-only"><span class="flex size-16 items-center justify-center rounded-full bg-white/40"><span class="material-symbols-outlined text-3xl text-[#67645c]">upload_file</span></span><span><span class="block font-medium text-[#67645c]">{{ $proof?->getClientOriginalName() ?? 'Unggah File (JPG, PNG, WEBP, PDF)' }}</span><span class="mt-1 block text-xs text-[#67645c]/60">Maksimal 5 MB</span></span></span>@error('proof')<p class="mt-2 text-sm text-[#ba1a1a]">{{ $message }}</p>@enderror<div wire:loading wire:target="proof" class="mt-2 text-sm text-[#44474e]">Mengunggah bukti…</div></label>
        @if ($proof && str_starts_with((string) $proof->getMimeType(), 'image/'))<img src="{{ $proof->temporaryUrl() }}" alt="Pratinjau bukti pembayaran" class="max-h-72 w-full rounded-xl bg-[#f4f4f2] object-contain">@endif
        <label class="block"><span class="mb-2 block text-xs font-semibold uppercase tracking-wider text-[#44474e]">Tanggal Pembayaran</span><input wire:model="paidAt" type="datetime-local" class="w-full rounded-xl border-0 bg-[#eeeeec] p-4 text-base outline-none focus:ring-2 focus:ring-[#031636]">@error('paidAt')<p class="mt-2 text-sm text-[#ba1a1a]">{{ $message }}</p>@enderror</label>
        <button wire:loading.attr="disabled" wire:target="submit" @disabled($paymentCategories->isEmpty()) class="flex w-full items-center justify-center gap-2 rounded-xl bg-[#031636] px-4 py-4 font-semibold text-white shadow-md transition active:scale-[.98] disabled:opacity-50"><span wire:loading.remove wire:target="submit" class="contents"><span class="material-symbols-outlined text-xl">send</span>Kirim Bukti Pembayaran</span><span wire:loading wire:target="submit">Mengirim…</span></button>
    </form>
</div>
